### ISSUE TITLE
Home screen form status not updated

### ISSUE THREAD

**Issue by lakshyagupta21** [opendatakit/skunkworks-crow#86] opened 2018-08-13 17:19 UTC
Status shown on home screen not updated when user taps on back button after reviewing the form but it gets updated in statistics screen.

Noticed in #74

**Comment by jddeep** [comment] 2019-02-27 14:53
@lakshyagupta21 i would like to work on this. Shall i? Kindly assign it. Thanks

**Comment by lakshyagupta21** [comment] 2019-03-02 20:22
Sure but can you check once whether this issue is reproducible or not.

**Comment by shobhitagarwal1612** [comment] 2019-03-20 19:51
Unable to reproduce

**Closed by shobhitagarwal1612** 2019-03-20 19:51 UTC
Labels: bug
