### ISSUE TITLE
Issue connecting Wifi Hotspot

### ISSUE THREAD

**Issue by lakshyagupta21** [opendatakit/skunkworks-crow#259] opened 2019-06-04 18:26 UTC
#### Software and hardware versions 
Android v7.1, device used... Xiomi Redmi 4

#### Problem description
Something got changed in recent PRs due to which in Android 7.1 its not able to connect to wifi hotspot. It shows message 'Connecting to wifi'.

#### Steps to reproduce the problem
1. Send forms.
2. Try connecting to ODK-SKUNKWORKS wifi network
3. Sometimes it gets stuck on the same dialog showing Connecting to wifi message with cancel button and sometimes it shows Network Unreachable in the dialog.
#### Expected behavior
It should connect to wifi network.
#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by huangyz0918** [comment] 2019-07-10 14:10
@lakshyagupta21 I also noticed this issue, but if I wait longer, the form can still be delivered sometimes. Sometimes I just got an error with timeout, I think whether success or not depends on the network environment, it's not a bug.
```
1970-01-07 14:17:58.889 12593-14150/org.odk.share E/DownloadJob: java.net.ConnectException: failed to connect to /192.168.43.1 (port 50918) from /192.168.43.234 (port 39266) after 2000ms: isConnected failed: ECONNREFUSED (Connection refused)
        at libcore.io.IoBridge.isConnected(IoBridge.java:273)
        at libcore.io.IoBridge.connectErrno(IoBridge.java:188)
        at libcore.io.IoBridge.connect(IoBridge.java:130)
        at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:129)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:356)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:357)
        at java.net.Socket.connect(Socket.java:616)
        at org.odk.share.tasks.DownloadJob.setupDataStreamsAndReceive(DownloadJob.java:148)
        at org.odk.share.tasks.DownloadJob.initJob(DownloadJob.java:124)
        at org.odk.share.tasks.DownloadJob.onRunJob(DownloadJob.java:106)
        at com.evernote.android.job.Job.runJob(Job.java:132)
        at com.evernote.android.job.JobExecutor$JobCallable.runJob(JobExecutor.java:191)
        at com.evernote.android.job.JobExecutor$JobCallable.call(JobExecutor.java:176)
        at com.evernote.android.job.JobExecutor$JobCallable.call(JobExecutor.java:159)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
        at libcore.io.IoBridge.isConnected(IoBridge.java:262)
```

**Comment by huangyz0918** [comment] 2019-07-18 02:40
I checkout to commit [5a72504e537fd0c22f878d38ce7337d0d1510877](https://github.com/opendatakit/skunkworks-crow/commit/5a72504e537fd0c22f878d38ce7337d0d1510877), and this issue still exists. 

```
1970-01-15 03:00:54.720 6936-6936/org.odk.share D/WifiActivity: ODK-SKUNKWORKS-odk-skunkworks  CONNECTING
1970-01-15 03:00:54.724 6936-6936/org.odk.share D/WifiActivity: ODK-SKUNKWORKS-odk-skunkworks  DISCONNECTED
1970-01-15 03:00:54.923 6936-6936/org.odk.share D/WifiActivity: [org.odk.share.network.WifiNetworkInfo@1eac680]
1970-01-15 03:00:56.085 6936-6936/org.odk.share D/WifiActivity: ODK-SKUNKWORKS-odk-skunkworks  CONNECTING
1970-01-15 03:00:56.089 6936-6936/org.odk.share D/WifiActivity: ODK-SKUNKWORKS-odk-skunkworks  DISCONNECTED
1970-01-15 03:01:02.494 6936-6936/org.odk.share D/WifiActivity: [org.odk.share.network.WifiNetworkInfo@59080fe]
1970-01-15 03:01:06.010 6936-6936/org.odk.share D/WifiActivity: ODK-SKUNKWORKS-odk-skunkworks  IDLE

```

**Comment by huangyz0918** [comment] 2019-07-21 03:32
@opendatakit-bot claim

**Comment by huangyz0918** [comment] 2019-07-26 02:56
@opendatakit-bot label "needs reproduction"

**Comment by huangyz0918** [comment] 2019-07-27 08:04
@opendatakit-bot label "needs discussion"

**Comment by huangyz0918** [comment] 2019-08-06 09:47
I think this issue is no longer active, but not sure. 
It would be appreciated if you can help to test and see if this issue can be reproduce again.
@lakshyagupta21  @shobhitagarwal1612 @iadeelzafar @DreamyPhobic @Chromicle

**Comment by Chromicle** [comment] 2020-03-27 08:55
I just tested @huangyz0918 transferring of forms done as expected, you can close this issue

**Comment by huangyz0918** [comment] 2020-03-27 09:12
Thanks @Chromicle !

**Closed by huangyz0918** 2020-03-27 09:12 UTC
Labels: needs discussion
