### ISSUE TITLE
App Crashes on pressing send button in Android pie

### ISSUE THREAD

**Issue by sarrocks1** [opendatakit/skunkworks-crow#186] opened 2019-03-08 09:40 UTC
Android v9, device - Nokia 7 plus..

Problem - App crashes when send button is pressed

Steps - In Android v9 , Nokia 7 plus, Select any form and press send button. The activity(page) refreshes once and the typical app has crashed message is shown.

I am attaching screenshot of the crash below. 

![skunk-bug](https://user-images.githubusercontent.com/29746985/54020635-3aec6380-41b4-11e9-83ee-b60deb39f4a8.png)

**Comment by Chromicle** [comment] 2019-03-08 11:08
@sarrocks1 yesterday I also Used the Android 9 of pie I didn't get these type of error

**Comment by lakshyagupta21** [comment] 2019-03-08 14:44
@sarrocks1 Can you check whether PR #155 is working fine or not on your device.

**Comment by sarrocks1** [comment] 2019-03-08 16:43
@lakshyagupta21  Nope , it doesn't work. I guess it must be device problem rather than Android v9 problem.

**Comment by shobhitagarwal1612** [comment] 2019-03-08 17:49
Can you paste the error thrown in the logcat?

**Comment by sarrocks1** [comment] 2019-03-09 06:48
@shobhitagarwal1612  @lakshyagupta21  @Chromicle  So apparently , I had the version of app before pr #165. I installed the latest version and all is working well.

What has been done to ensure that issue has been resolved -
Sent 5 forms from Nokia 7 plus , android v9 to Samsung galaxy J7 , android v7
and vice-versa without any fail.

Looks like the error was resolved in one of the recent pr's.

Thank You.

**Comment by sarrocks1** [comment] 2019-03-09 06:48
@shobhitagarwal1612 @lakshyagupta21 @Chromicle So apparently , I had the version of app before pr #165. I installed the latest version and all is working well.

What has been done to ensure that issue has been resolved -
Sent 5 forms from Nokia 7 plus , android v9 to Samsung galaxy J7 , android v7
and vice-versa without any fail.

Looks like the error was resolved in one of the recent pr's.

Thank You.

**Comment by sarrocks1** [comment] 2019-03-11 18:43
**Problem(updated)** - The above error occurs only when any device is already connected to my mobile hotpot.

**Steps** - I connected my laptop to my mobile hotspot and tried sending the forms , which gave the above bug. I tried by connecting other devices to my hotspot and the bug still persists.
I switched off my hotspot and pressed send , the app worked perfectly fine.

**Solution** - I guess that the app is not able to disconnect from the already setup wifi hotspot.
We can make list of devices with their os version to narrow down root of problem.

**Comment by udhay24** [comment] 2019-03-20 08:37
I guess the problem is with location. if the location is disabled in our phone the app crashes while sending and it happens in all the version of android

**Comment by Chromicle** [comment] 2019-03-20 11:53
> **Problem(updated)** - The above error occurs only when any device is already connected to my mobile hotpot.
> 
> **Steps** - I connected my laptop to my mobile hotspot and tried sending the forms , which gave the above bug. I tried by connecting other devices to my hotspot and the bug still persists.
> I switched off my hotspot and pressed send , the app worked perfectly fine.
> 
> **Solution** - I guess that the app is not able to disconnect from the already setup wifi hotspot.
> We can make list of devices with their os version, having this bug to narrow down root of problem.

yeah @udhay24 I tried now it is working fine expect showing QR code. is it a problem is it particular that we should on the location to send forms I tested on other apps it is working without location turned on

**Comment by udhay24** [comment] 2019-03-20 13:49
@Chromicle but I am facing some problem with it. I have opened a new issue #219 for it. can you take a look at that issue.

**Comment by sarrocks1** [comment] 2019-03-20 19:28
@udhay24  I am not facing #219. But still the app crashes if hotspot is already connected with different device.

**Comment by shobhitagarwal1612** [comment] 2019-03-24 05:15
Closing as this would be resolved along with issue https://github.com/opendatakit/skunkworks-crow/issues/191

**Closed by shobhitagarwal1612** 2019-03-24 05:15 UTC
