### ISSUE TITLE
Migrating to androidX

### ISSUE THREAD

**Issue by udhay24** [opendatakit/skunkworks-crow#189] opened 2019-03-09 17:16 UTC
####  Problem description
1.I feel we should add Kotlin support to help new contributors and let developers to take advantage of the language 

2. Another idea I would to propose is to migrate from android support library to androidX components

**Comment by udhay24** [comment] 2019-03-09 17:18
@shobhitagarwal1612, @lakshyagupta21 can i work this issue?

**Comment by shobhitagarwal1612** [comment] 2019-03-09 18:06
I agree that coding in Kotlin has its own pros and cons. What made you propose that Kotlin would be an enhancement to the project? Does it provide any specific advantages over the current structure?
Also, what would be the cons of doing so?

**Comment by udhay24** [comment] 2019-03-10 05:56
We should be considering migrating to AndroidX as support library will not be receiving anymore updates. as the android documentation says

> You can continue to use the support library. Historical artifacts (those versioned 27 and earlier, and packaged as android.support.*) will remain available on Google Maven. However, all new library development will occur in the AndroidX library. 

> We recommend using the AndroidX libraries in all new projects. You should also consider migrating existing projects to AndroidX as well.

**Comment by shobhitagarwal1612** [comment] 2019-03-10 06:09
Sounds reasonable. But before moving forward, we need to have a plan. Since this is a live project, any regressions cannot be risked. 

1. Identify what's relying on support library
2. What would be the impact on current functionalities or behaviour?
3. Is there a compatibility support issue with the current gradle or targeted SDK version
4. How much effort would be required for this?

I'd recommend you to go through the codebase and try to answer the above questions. Once we have a clear plan, then we can proceed with migrating to androidx


But I don't feel so good about moving to kotlin. So let's drop that idea for now.

**Comment by udhay24** [comment] 2019-03-10 07:10
@opendatakit-bot -claim

**Comment by udhay24** [comment] 2019-03-10 07:12
@opendatakit-bot claim

**Comment by udhay24** [comment] 2019-03-10 07:12
@opendatakit-bot claim --force

**Comment by udhay24** [comment] 2019-03-10 07:13
@opendatakit-bot claim --force.

**Comment by udhay24** [comment] 2019-03-10 07:13
@opendatakit-bot claim --force

**Comment by udhay24** [comment] 2019-03-10 07:22
###  codes relying on support library: 
AppCompatActivity and fragments , CustomViews(Wifi View),RecyclerView
###  compatibility support issue with the current gradle or targeted SDK version
**compiletimeSdk version** needs to be updated to 27 or 28, 
**com.android.tools.build:gradle** needs to be updated to latest version,
**Gradle.properties** 2 new flags need to be added 
### impact on current functionalities or behaviour:
there may be problems with merging new pull request due to package naming conflicts

**Comment by udhay24** [comment] 2019-03-22 02:48
yeah i am still working on the issue

**Comment by udhay24** [comment] 2019-03-27 07:22
@opendatakit-bot claim

**Closed** 2019-04-01 19:24 UTC
Labels: in progress, needs discussion
