### ISSUE TITLE
Hotspot Password dialog is accepting empty field

### ISSUE THREAD

**Issue by rohitnitk** [opendatakit/skunkworks-crow#244] opened 2019-04-09 07:03 UTC
#### Software and hardware versions 
Android v8.1, device used Redmi Note 5

#### Problem description
 dialog box for hotspot password is accepting empty input field, thus saving password as empty string
#### Steps to reproduce the problem
1.Setting ->Enable checkbox for 'Set Password'
2. Go to 'Set Hotspot Password' 
3. Clear input and press 'OK' button
#### Expected behavior
It should not accept the empty input

**Comment by iadeelzafar** [comment] 2019-04-09 10:29
Duplicate of #233

**Comment by Chromicle** [comment] 2019-04-09 11:38
Close this issue @rohitnitk if #233 is merged then this issue will be solved

**Comment by jhbiggs** [comment] 2019-06-08 16:27
Just made a pull request with a solution for this issue.

**Comment by manit-alokbatham** [comment] 2019-11-27 09:04
@opendatakit-bot claim

**Closed** 2019-11-30 07:14 UTC
