### ISSUE TITLE
Feature request, Instead of typing the destination directory ,user can choose the destination directory by opening file explorer dialog

### ISSUE THREAD

**Issue by rheo-chiti** [opendatakit/skunkworks-crow#357] opened 2020-02-19 11:14 UTC
#### Software and hardware versions 
Android vx.x.x, device used...
Android v9.0, Realme 1

#### Problem description
Currently for selecting the destination(```ODK Destination Directory```),user has to manually type the destination. It would be a nice improvement if the user has to choose the folder from file explorer instead.

#### Steps to reproduce the problem
1. Open the app
2. Go to Settings
3. Select the ODK Destination Directory 
#### Other information 
I am thinking of adding an icon there and when user presses the icon a file explorer dialog will open and user can select the directory

**Comment by rheo-chiti** [comment] 2020-02-19 11:24
Hi @huangyz0918  @lakshyagupta21 can you please give a feedback on this feature?
I will work on a PR soon

**Comment by Chromicle** [comment] 2020-02-19 12:30
Hello, @rheo-chiti thanks for raising the issue, but it looks like a duplicate of #250 and I raised PR for that.
if you have no queries for this, please close this issue

**Comment by rheo-chiti** [comment] 2020-02-19 14:21
@Chromicle ,Sorry I couldn't see that PR(it wasn't merged), next time I will check at the existing unclosed PR's too🙂

**Closed** 2020-02-19 14:46 UTC
